### ISSUE TITLE
ERROR! no action detected in task.

### ISSUE THREAD

**Issue by microcosm** [gunzy83/ansible-makepkg#4]
Hi,

I've been trying to run the example exactly as specified in the readme. But I just keep getting this error:

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/macuser/Developer/arch/library/playbook.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Ensure aurvote is installed
      ^ here

The error appears to have been in '/Users/macuser/Developer/arch/library/playbook.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Ensure aurvote is installed
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Here's my playbook:

```
---
- hosts: all
  vars:
  remote_user: root
  become: yes
  tasks:
    - name: Ensure aurvote is installed
      makepkg:
        name: aurvote
        state: present
```

It's as though the module isn't being parsed by ansible. However it is right there from when I cloned it, as specified in the readme:
```
$ ls -la library
total 120
drwxr-xr-x  7 macuser  staff    238 Feb 26 20:34 .
drwxr-xr-x  8 macuser  staff    272 Feb 26 20:35 ..
-rw-r--r--  1 macuser  staff  35147 Feb 26 20:20 COPYING
-rw-r--r--  1 macuser  staff   1576 Feb 26 20:20 README.md
-rw-r--r--  1 macuser  staff  12246 Feb 26 20:20 makepkg
-rw-r--r--  1 macuser  staff      8 Feb 26 19:51 playbook.retry
-rw-r--r--  1 macuser  staff    167 Feb 26 20:36 playbook.yml
```

Do you have any ideas?

**Comment by jlgaddis** [comment]
@microcosm -- I don't use this particular module but it appears that maybe you don't have all your files in the correct location; that is, your file/directory structure is incorrect. Ansible even told you so right in the error message:  "_... incorrect module path._"

As a general rule, you'll probably want to follow Ansible's [recommended directory layout](https://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout) -- at least until you get more familiar with Ansible.

In order for Ansible to find it, you need to install this module in the correct location. The instructions show you how to do that -- but you didn't follow those. It's reasonable to expect that you'll run into issues -- even when trying to "run the example exactly as specified in the readme" -- if you don't follow the instructions.

If you **had** followed the instructions, you would have a directory named `ansible-makepkg/` inside your `library/` directory, the `makepkg` file would be in that directory, and you wouldn't have ran into these errors.

But, let's see if we can get you up and running, anyways...

First, throw away what you already did and start from scratch. Create a new directory just for your Ansible stuff. Let's use `/Users/macuser/Developer/ansible/`. This will be the top-level directory and your reference point when setting up your directory layout as described at the above link. It is the directory your `playbook.yml` will reside in. Go ahead and copy/move it there now.

Next, create the sub-directories you need as shown in that same recommended layout, including the `library/` directory.

Then, descend into the `library/` directory and clone this repository [as shown in the README](https://github.com/gunzy83/ansible-makepkg/blob/master/README.md). During the clone process, a new `ansible-makepkg/` directory will be created. Inside that directory, you'll find the `makepkg` module. Alternatively, you can download the `makepkg` file using any other means (as it appears you might have done originally), but it is imperative that you make sure to put it in the right location!

You should now have (at least) these directories and files:

* `/Users/macuser/Developer/ansible/`
* `/Users/macuser/Developer/ansible/playbook.yml`
* `/Users/macuser/Developer/ansible/library/`
* `/Users/macuser/Developer/ansible/library/ansible-makepkg/`
* `/Users/macuser/Developer/ansible/library/ansible-makepkg/makepkg`

If you cloned this repository, you'll also see:

* `/Users/macuser/Developer/ansible/library/ansible-makepkg/COPYING`
* `/Users/macuser/Developer/ansible/library/ansible-makepkg/README.md`

Last, move back to the `/Users/macuser/Developer/ansible/` directory and run your playbook:

    $ cd /Users/macuser/Developer/ansible/
    $ ansible-playbook playbook.yml

_Note:_ You may need to supply some additional parameters (such as pointing to an inventory file).

Good luck.

**Comment by microcosm** [comment]
Thanks for your detailed and helpful reply. I'm looking through this...

**Comment by gunzy83** [comment]
@microcosm the plugin has to the installed in your library directory as mentioned by @jlgaddis. If you are still having issues please reopen this issue and I will work through it with you.

@jlgaddis thanks for responding to this issue in my absence (day job has been extremely taxing). I really appreciate it!
